apiVersion: v1
kind: ConfigMap
metadata:
  name: esme-app-config
  namespace: esme-tp-julesmlrd
  labels:
    app: esme-devops-app
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  MESSAGE: "Deploye par Jules Milard - ESME 2025"

