apiVersion: v1
kind: Service
metadata:
  name: esme-app-loadbalancer
  namespace: esme-tp-julesmlrd
  labels:
    app: esme-devops-app
    service-type: external
spec:
  type: LoadBalancer
  selector:
    app: esme-devops-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  sessionAffinity: None

